services:
  - type: web
    name: laravel-app
    runtime: docker
    plan: free
    branch: main
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true

